apiVersion: v1
kind: Pod
metadata:
  name: network-tools
  labels:
    app: network-tools
spec:
  containers:
    - name: network-tools
      image: alpine:latest
      command:
        - sh
        - -c
        - >
          apk update &&
          apk add --no-cache iputils bind-tools curl wget netcat-openbsd traceroute &&
          sleep 3600;
      stdin: true
      tty: true
