apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor
  namespace: argocd
  labels: 
    studying: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Alves0611/studying-argocd.git
    path: k8s
    targetRevision: HEAD
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  info: 
    - name: projeto
      value: studying gitops 